version: '{build}'
image: Visual Studio 2017
init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Write-Host "We now have a tagged release. Proper."
        Write-Host "Tag is $Env:APPVEYOR_REPO_TAG_NAME"
        $env:APPVEYOR_BUILD_VERSION=$env:APPVEYOR_REPO_TAG_NAME
        Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME"
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        $spl = $tag.Split("-")[0]
        Update-AppveyorBuild -Version "$spl.$Env:APPVEYOR_BUILD_VERSION-wip"
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION"

before_build:
- cmd: >-
    nuget restore

# version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  project: SpeckleCore.sln
  verbosity: minimal
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: n4EiHDLVSLjOzqT7OOOg3US3PWs6fNsOaGpyT/EFBKrTKl/1wMmmKt73MNuTngD+
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  on:
    appveyor_repo_tag: true
notifications:
- provider: Slack
  incoming_webhook:
    secure: 9Kt/ImvGdsQ/dzmRdSaMIG+BO0R29MOJC7eZZnK5m5TyWwE+4nofEcYlb/r4lh9Z1Dx/bR+7oQtgAYO3W5s+qJshkT6Is9irYw3TfMZX7/M=
  channel: '#devtalk'
  template: Build <{{buildUrl}}|#{{buildVersion}}> (<{{commitUrl}}|{{commitId}}>) of {{repositoryName}}@{{branch}}) by {{commitAuthor}} {{status}} in {{duration}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
configuration:
  - Release
